### ISSUE TITLE
Error in base_format.

### ISSUE THREAD

**Issue by DawnYe** [pzhaonet/bookdownplus#17]
I've tried to build a PDF book :
==> rmarkdown::render_site(output_format = 'bookdown::pdf_book', encoding = 'UTF-8')

But error occurred as blow:

[](url)![image](https://user-images.githubusercontent.com/21993401/30842866-e6d297f2-a2b7-11e7-9c82-a280a5a308ca.png)

Error in base_format(toc = toc, number_sections = number_sections, fig_caption = fig_caption,  : 
  unused arguments (toc_unnumbered = FALSE, toc_appendix = TRUE, quote_footer = c("\\begin{flushright}", "\\end{flushright}"))

I don't know how to handle this, is there a possibility that you could give me a hand? Thanks.

**Comment by pzhaonet** [comment]
Thanks for the feedback. I would suggest that you could use RStudio rather than windows cmd. If the problem still exists, please provide your `sessionInfo()`.

**Comment by DawnYe** [comment]
Thanks for your reply. RStudio actually was used in this project. I updated the R session to MRO-3.4.1 and re-installed all the packages required. Luckily, the error above was disappear. But compiling PDF file still failed.
![capture-2](https://user-images.githubusercontent.com/21993401/30854644-d88248f0-a2e4-11e7-9268-56ee730d8f4e.PNG)

`sessionInfo()`:
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bookdownplus_1.3.1   RevoUtilsMath_10.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     bookdown_0.5     digest_0.6.12    rprojroot_1.2    backports_1.1.0  magrittr_1.5     evaluate_0.10.1 
 [8] highr_0.6        stringi_1.1.5    rstudioapi_0.6   rmarkdown_1.6    RevoUtils_10.0.5 tools_3.4.1      stringr_1.2.0   
[15] yaml_2.1.14      compiler_3.4.1   htmltools_0.3.6  knitr_1.17

**Comment by pzhaonet** [comment]
A LaTeX error is shown. Please try Yihui's [mini example of bookdown](https://github.com/yihui/bookdown-minimal), or [bookdown demo](https://github.com/rstudio/bookdown-demo). Bookdownplus is based on bookdown. Firstly make sure that bookdown works properly on you computer. If not, please contact @yihui for further discussion. If bookdown works properly and you sill have this problem, it means that the problem is from bookdownplus and please let me know.

**Comment by DawnYe** [comment]
Hi,@pzhaonet. I tried as you said. `bookdown` works properly on my compter.

![cap-3](https://user-images.githubusercontent.com/21993401/30919187-40d9102a-a3d3-11e7-9ed7-859592636db1.PNG)

But when it comes to `bookdownplus-textbook` , the same error happened again.
![cap-4](https://user-images.githubusercontent.com/21993401/30919536-41f2290a-a3d4-11e7-97ad-8fa124c88c10.PNG)
![cap-5](https://user-images.githubusercontent.com/21993401/30919541-4952955e-a3d4-11e7-9af8-b7d56b1bcd4c.PNG)

**Comment by pzhaonet** [comment]
Great! So the problem is from bookdownplus.
Please try the template yihui_mini:
```
bookdownplus::bookdownplus(template = "yihui_mini")
```
If you get /book/yihui_mini.pdf properly, it means that the problem may be from the default template 'thesis_classic'. You can try other available templates to see which works well. `bookdownplus::template()` will show all the available templates. Search your latex error online.

If you cannot get  /book/yihui_mini.pdf properly, please let me know. It means the problem is from bookdown() function itself. 

BTW, please do not paste your error message in images. Paste the text. Thank you.

**Comment by DawnYe** [comment]
Sorry for these error images.
I tried the template yihui_mini: 
`bookdownplus::bookdownplus(template = "yihui_mini")`

Although there were some warning messages:

> Warning messages:
1: running command '"bibtex" "yihui_mini.aux"' had status 2 
2: running command '"bibtex" "yihui_mini.aux"' had status 2 
3: In file.remove(paste0(template, ".lol")) :
  cannot remove file 'yihui_mini.lol', reason 'No such file or directory'

But `yihui_mini.pdf` compiled properly.

**Comment by pzhaonet** [comment]
Well done! It seems something wrong with your LaTeX. Is it the newest version from CTeX? If not, I would suggest that you might update or reinstall CTeX.

Regarding the Chinese support, unfortunately thesis_classic template does not support Chinese. Only those templates with '_zh' support Chinese. Please read the related explanation in bookdownplus Textbook: <https://bookdown.org/baydap/bookdownplus/advanced.html#chinese>
