### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by petzi53** [pzhaonet/bookdownplus#18]
Hi @pzhaonet,

Thank you for you fine package which is very useful for people like me with not so much experience! 

I am using R version 3.4.2 (2017-09-28) with RStudio Version 1.1.364.
I noticed several installation problems which I would like to report:

1.  The CRAN-Version of your package (1.3.0) does not generate a bookdownplus.Rproj file as you wrote in your book chapter 2.3 step 2. But the developer version (1.3.1) does generate this file.
2. I believe that the installation procedure as described in your book is misleading. I am working on a Mac with OSX (os sierra) and noticed following problems:

- The produced bookdownplus.Rproj is not recognized as a 'real' .Rproj file, but as a normal text file. There is no build command available.
- If you have a 'real' .Rproj file than you can't open it as a file but RStudio opens the project preference window
- The shortcut mentioned in your book 'ctrl-shift-b' does not work on a Mac. Here it is 'cmd-shift-b'
- But this shortcut does only work if you are working in a 'real' RStudio project.

So my recommendation is to change your description after the complete installation procedure. The new description should contain the following (new or modified) instructions:

1. Start a new RStudio project in a new folder
2. load the bookdownplus package by typing `library(bookdownplus)` in the console window (or select the  "Packages" Tab in the lower right pane, search for the bookdownplus package and tick its checkmark)
3. Then continue with the end of your step 1 "Although there are many arguments…" and add the complete step 2 of your installation procedure
4. Then continue with your Step 3: Build your book but with the following text: After writing some texts, select the "Build"-Tab in the upper right pane and either click on the "Build Book" tab for producing all formats or select the desired format. You can also use the shortcut `ctrl-shift-b` (Windows) or `cmd-shift-b` (Mac) for building all formats.

Another issue: When you build the book a pandoc warning appears:
`[pandoc warning] --chapters is deprecated. Use --top-level-division=chapter instead.`

In the long run it would be nice if your package could be default package for the installation procedure in the soon released new version in RStudio. In the preview version, I am using are different choices for creating a new RStudio project. One is to start a bookdown project. It would be nice if Yihui Xie could agree to use your templates for a new bookdown project via RStudio.

Hopefully my comments are of value for you…

PS.: I forgot to mention: With my proposal for a changed instruction you would not need  to generate a `.Rproj`-file because it is generated by RStudio itself.

**Comment by pzhaonet** [comment]
Hi, @petzi53. Thank you so much for your comments. They mean a lot to me. Your feedback is not only a great improvement for bookdownplus, but also an surprising encouragement to me. Please see my reply as follows.

1.  The bookdownplus.Rproj is not generated by bookdownplus v1.3.0, but by v1.3.1. It was my carelessness that I messed up with my scripts before uploading to CRAN. I am sorry for that. Now v1.3.1 cannot be uploaded to CRAN because it is larger than 5 MB. I have to spend some time in reducing the size.

2. Regarding the procedure on Mac OS, bookdownplus has been tested only on Windows. I do not have a Mac, so it is difficult for me to test it, although it should have. I have received very good comments from Mac users, including you, which would definitely help a lot in the future when I am able to buy (hopefully) a Mac in the future. I will specify this in the bookdownplus textbook.

Let's come to the bookdownplus.Rproj file again. When the first version of bookdownplus was released, RStudio did not support creating a bookdown project yet. Users had to download an .Rproj file from @yihui's demo before they were able to build a book from the toolbar or shortcut. This was why bookdownplus generates a bookdownplus.Rproj file for users. Now the new version of RStudio is able to create a bookdown project from the menu, it might be a more friendly way than bookdownplus.Rproj to some users. Well, bookdownplus.Rproj generated by bookdownplus is still my favorite way, because I get used to it. I will add an argument in `bookdownplus()` function to choose if .Rproj is generated or not.

For the long run I totally agree with you. It would be great that RStudio could provide some bookdown templates, not necessarily from bookdownplus, in the future. In fact, I developed bookdownplus just because there were/are no official templates from bookdown -- @yihui is too busy, and I could not wait. bookdown is too attractive to me. This motivation was written at the beginning of the bookdownplus textbook. 

To be honest, the structures of bookdownplus templates are not satisfactory, although they do work well for my everyday use. I am neither an expert in R nor in LaTeX, which is a limitation for me to write fancy scripts. I am looking forward to more contributors to bookdownplus, so that bookdownplus could be improved. It might be a pilot library for official bookdown templates.

Thank you again for your nice feedback.

**Comment by yihui** [comment]
Yep, I'm here just to confirm I'm busy :) 

Typically my priority is on developing general frameworks instead of considering specific use cases of a general framework. For example, I didn't invest much time on bookdown templates (I could, but I deliberately chose not to), and that is a perfect gap that bookdownplus can fill out. For the same reason, I don't want to work too hard on website templates for blogdown.

**Comment by petzi53** [comment]
Hi @pzhaonet, Thank you for your answer. I understand fully these limitations and had already abandoned my trial with bookdownplus in the moment. I am still struggling with the standard bookdown project ;-)

And thank you @yihui also for your reply. I agree with your decision: it would be a waste of your programming expertise to look into templates. I believe when bookdown is becoming more popular there will people who are interested to develop templates for different use cases.

**Comment by pzhaonet** [comment]
@petzi53 @yihui I was wondering if it is possible to test the compatibility of a program for Mac OS without buying a Mac?

**Comment by petzi53** [comment]
Sorry, I just know how to test windows programs on a mac. I have no experience from the windows perspective. The only thing I could offer is to test it for you and to report it to you.
